<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="SAIFUR-9A8B7153"><DocLocation><![CDATA[C:\Documents and Settings\Administrator\Desktop\QTP\AllTest\MCDDFFN\TCDDF]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[TCDDF]]></DName>
<Res><![CDATA[Res36]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:08]]></Time>
<TimeTick>1355684828</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:08]]></Time>
<TimeTick>1355684828</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="31" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="31" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Mortgage Calculator]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:17]]></Time>
<TimeTick>1355684837</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Mortgage Calculator]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:17]]></Time>
<TimeTick>1355684837</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[param[homevalue].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["400000"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:17]]></Time>
<TimeTick>1355684837</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[homevalue].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[param[credit].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Fair"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:20]]></Time>
<TimeTick>1355684840</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[credit].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[param[principal].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["350000"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:23]]></Time>
<TimeTick>1355684843</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[principal].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[param[rp].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["New Purchase"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:27]]></Time>
<TimeTick>1355684847</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[rp].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[param[interest_rate].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:30]]></Time>
<TimeTick>1355684850</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[interest_rate].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[param[term].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["50"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:34]]></Time>
<TimeTick>1355684854</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[term].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[param[start_month].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Dec"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:38]]></Time>
<TimeTick>1355684858</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[start_month].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[param[start_year].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#23"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:42]]></Time>
<TimeTick>1355684862</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[start_year].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[param[property_tax].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1.5"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:45]]></Time>
<TimeTick>1355684865</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[property_tax].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[param[pmi].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0.7"]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:50]]></Time>
<TimeTick>1355684870</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" Source="Action1" SourceLine="28" >
<Disp><![CDATA[param[pmi].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Calculate.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/16/2012 - 14:07:50]]></Time>
<TimeTick>1355684870</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="46" Source="Action1" SourceLine="46" >
<Disp><![CDATA[Calculate.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Action1" SourceLine="28" >
<Disp><![CDATA[Mortgage Calculator]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Action1" SourceLine="28" >
<Disp><![CDATA[Mortgage Calculator]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/16/2012 - 14:07:07" eTime="12/16/2012 - 14:07:50" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[TCDDF Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="12/16/2012 - 14:07:06" eTime="12/16/2012 - 14:07:50" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test TCDDF Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>